config/routes.rb
Rails.application.routes.draw do 
  resources :denuncia
  resources :institucioncatalogos
  resources :catalogos
  resources :institucions
  
  root :to => "institucions#index"

  resources :institucions do
    resources :institucioncatalogos
  end

  devise_for :usuarios, 
  	path: 'auth', 
  	path_names: { 
  		sign_in: 'login', 
  		sign_out: 'logout', 
  		password: 'secret', 
  		confirmation: 'verification', 
  		unlock: 'unblock', 
  		registration: 'register', 
  		sign_up: 'let_me_in' }
end

app/models/catalogo.rb
class Catalogo < ApplicationRecord
	before_save :to_upper

	has_many :denunciums
	has_many :institucioncatalogos

	validates :valor, :descripcion, presence: true
	validates :valor, uniqueness: true 
	validates :valor, length: { maximum: 50 }
	validates :descripcion, length: { maximum: 150 }
end

app/controllers/catalogos_controller.rb
class CatalogosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_catalogo, only: [:show, :edit, :update, :destroy]

  # GET /catalogos
  # GET /catalogos.json
  def index
    @catalogos = Catalogo.all
  end

  # GET /catalogos/1
  # GET /catalogos/1.json
  def show
  end

  # GET /catalogos/new
  def new
    @catalogo = Catalogo.new
  end

  # GET /catalogos/1/edit
  def edit
  end

  # POST /catalogos
  # POST /catalogos.json
  def create
    @catalogo = Catalogo.new(catalogo_params)

    respond_to do |format|
      if @catalogo.save
        format.html { redirect_to @catalogo, notice: 'Catalogo se ha creado exitosamente.' }
        format.json { render :show, status: :created, location: @catalogo }
      else
        format.html { render :new }
        format.json { render json: @catalogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catalogos/1
  # PATCH/PUT /catalogos/1.json
  def update
    respond_to do |format|
      if @catalogo.update(catalogo_params)
        format.html { redirect_to @catalogo, notice: 'Catalogo se ha actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @catalogo }
      else
        format.html { render :edit }
        format.json { render json: @catalogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catalogos/1
  # DELETE /catalogos/1.json
  def destroy
    @catalogo.destroy
    respond_to do |format|
      format.html { redirect_to catalogos_url, notice: 'Catalogo se ha eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catalogo
      @catalogo = Catalogo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def catalogo_params
      params.require(:catalogo).permit(:valor, :descripcion)
    end
end

app/helpers/catalogos_helper.rb
module CatalogosHelper
end

app/views/catalogos/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_with(model: catalogo, local: true) do |form| %>
      <% if catalogo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(catalogo.errors.count, "error") %> prohibited this catalogo from being saved:</h2>

          <ul>
          <% catalogo.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-row">           
        <div class="form-group mb-2 col-md-4"> 
          <%= form.label :valor %>
        </div> 
        <div class="form-group mb-2 col-md-8">
          <%= form.text_field :valor, id: :catalogo_valor %>
        </div>
      </div>

      <div class="form-row">           
        <div class="form-group mb-2 col-md-4">
          <%= form.label :descripcion %>
        </div> 
        <div class="form-group mb-2 col-md-8">
          <%= form.text_field :descripcion, id: :catalogo_descripcion %>
        </div>
      </div>
      <br>
      <div class="actions">
        <button type="submit" class="button btn btn-primary"><i class='fa fa-save'></i> Guardar</button>
      </div>
    <% end %>
  </div>
</div>

app/views/catalogos/edit.html.erb
<!-- Titlebar
================================================== -->
<div id="titlebar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('titulos.catalogo') %></h2>
        <!-- Breadcrumbs -->
        <nav id="breadcrumbs">
          <ul>
            <li><%= inicio %></li>
            <li><%= link_to t('titulos.catalogo'), catalogos_path %></li>
            <li><%= t('titulos.editar') %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- Content
    ================================================== -->
<section class="container">  
	<%= render 'form', catalogo: @catalogo %>
</section>

app/views/catalogos/index.html.erb
<!-- Titlebar
================================================== -->
<div id="titlebar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('titulos.catalogo') %></h2>
        <!-- Breadcrumbs -->
        <nav id="breadcrumbs">
          <ul>
            <li><%= inicio %></li>
            <li>Catalogo</li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- Content
    ================================================== -->
<section class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">    
    <div class="col-lg-12">
      <table class="basic-table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Código</th>
            <th scope="col"><%= t('activerecord.attributes.catalogo.valor') %></th><!--style="width: 60%"-->
            <th scope="col"><%= t('activerecord.attributes.catalogo.descripcion') %></th>
            <th scope="col"><%= t('titulos.acciones') %></th>
          </tr>
        </thead>
        <tbody>
          <% @catalogos.each do |catalogo| %>
            <tr>
              <td><%= catalogo.id %></td>
              <td><%= catalogo.valor %></td>
              <td><%= catalogo.descripcion %></td>
              <td>
                <div class="btn-group" role="group">
                  <%= link_to t('botones.show'), catalogo, :class => 'button btn btn-secondary boton-xs' %>
                  <%= link_to t('botones.editar'), edit_catalogo_path(catalogo), :class => 'button btn btn-info boton-xs' %>
                  <%= link_to t('botones.eliminar'), catalogo, method: :delete, data: { confirm: 'Seguro que desea eliminar este catalogo?' }, :class => 'button btn btn-danger boton-xs' %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to t('botones.nuevo'), new_catalogo_path, :class => 'button btn btn-primary' %>
    </div>
  </div>
</section>

app/views/catalogos/new.html.erb
<!-- Titlebar
================================================== -->
<div id="titlebar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('titulos.catalogo') %></h2>
        <!-- Breadcrumbs -->
        <nav id="breadcrumbs">
          <ul>
            <li><%= inicio %></li>
            <li><%= link_to t('titulos.catalogo'), catalogos_path %></li>
            <li><%= t('titulos.nuevo') %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- Content
    ================================================== -->
<section class="container">  
	<%= render 'form', catalogo: @catalogo %>
</section>

app/views/catalogos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
	<div class="centrado">
		<form style="width: 350px;">  
			<div class="form-row">			     
        		<div class="form-group mb-2 col-md-4">            
		         	<p class="form-control text-primary"><%= t('activerecord.attributes.catalogo.valor') %>: </p>
		        </div> 
		        <div class="form-group mb-2 col-md-8">                       
		          	<p class="form-control"><%= @catalogo.valor %></p>	            	
		        </div>  
		    </div>	
		    <div class="form-row">			     
        		<div class="form-group mb-2 col-md-4">            
		         	<p class="form-control text-primary"><%= t('activerecord.attributes.catalogo.descripcion') %>: </p>
		        </div> 
		        <div class="form-group mb-2 col-md-8">                       
		          	<p class="form-control"><%= @catalogo.descripcion %></p>	            	
		        </div>  
		    </div>		    	    	      	
	    </form>
  	</div>
</div>

<%= link_to t('titulos.editar'), edit_catalogo_path(@catalogo) %> |
<%= link_to t('titulos.regresar'), catalogos_path %>