config/routes.rb
Rails.application.routes.draw do 
  resources :denuncia
  resources :institucioncatalogos
  resources :catalogos
  resources :institucions
  
  root :to => "institucions#index"

  resources :institucions do
    resources :institucioncatalogos
  end

  devise_for :usuarios, 
  	path: 'auth', 
  	path_names: { 
  		sign_in: 'login', 
  		sign_out: 'logout', 
  		password: 'secret', 
  		confirmation: 'verification', 
  		unlock: 'unblock', 
  		registration: 'register', 
  		sign_up: 'let_me_in' }
end

app/controllers/denuncia_controller.rb
class DenunciaController < ApplicationController
  #before_action :authenticate_usuario!, except: [:new, :create]
  before_action :set_denuncium, only: [:show, :edit, :update, :destroy]

  # GET /denuncia
  # GET /denuncia.json
  def index
    @denuncia = Denuncium.all
  end

  # GET /denuncia/1
  # GET /denuncia/1.json
  def show
  end

  # GET /denuncia/new
  def new
    combos()
    @denuncium = Denuncium.new
  end

  # GET /denuncia/1/edit
  def edit
    combos()
  end

  # POST /denuncia
  # POST /denuncia.json
  def create
    combos()
    @denuncium = Denuncium.new(denuncium_params)

    respond_to do |format|
      if @denuncium.save
        format.html { redirect_to denuncia_url, notice: 'Denuncia se ha creado exitosamente.' }
        format.json { render :show, status: :created, location: @denuncium }
      else
        format.html { render :new }
        format.json { render json: @denuncium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /denuncia/1
  # PATCH/PUT /denuncia/1.json
  def update
    combos()
    respond_to do |format|
      if @denuncium.update(denuncium_params)
        format.html { redirect_to denuncia_url, notice: 'Denuncia se ha actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @denuncium }
      else
        format.html { render :edit }
        format.json { render json: @denuncium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /denuncia/1
  # DELETE /denuncia/1.json
  def destroy
    @denuncium.destroy
    respond_to do |format|
      format.html { redirect_to denuncia_url, notice: 'Denuncia se ha eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  def getKey
    $keymaps
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_denuncium
      $keymaps = ""
      #$keymaps = "AIzaSyD4dj_2wQLx3iZ5oMOERIGKaRBqn4bwDj0"
      @denuncium = Denuncium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def denuncium_params
      params.require(:denuncium).permit(:fecha, :descripcion, :longitud, :latitud, :estado, :catalogo_id)
    end

    def combos
      #@valores = Catalogo.joins(:institucioncatalogo).where(institucioncatalogo: {institucion: })
      @valores  = Catalogo.all
    end
end

app/helpers/denuncia_helper.rb
module DenunciaHelper
end

app/views/denuncia/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_with(model: denuncium, local: true) do |form| %>
      <% if denuncium.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(denuncium.errors.count, "error") %> prohibited this denuncium from being saved:</h2>

          <ul>
          <% denuncium.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-row">           
        <div class="form-group mb-2 col-md-4">
          <%= form.label :fecha %>
        </div> 
        <div class="form-group mb-2 col-md-8">
          <%#= form.datetime_select :fecha, :ampm => true %>
          <%= form.text_field :fecha, data:{ provide:'datepicker' }, :class => 'form-control', :id => 'inicio' %>  
        </div>
      </div>

      <div class="form-row">           
        <div class="form-group mb-2 col-md-4">
          <%= form.label :descripcion %>
        </div> 
        <div class="form-group mb-2 col-md-8">
          <%= form.text_field :descripcion %>
        </div>
      </div>

      <div class="form-row">           
        <div class="form-group mb-2 col-md-4">
          <%= form.label :longitud %>
        </div> 
        <div class="form-group mb-2 col-md-8">
          <%= form.text_field :longitud, :id => 'longitud', :readonly => "true" %>
        </div>
      </div>

      <div class="form-row">           
        <div class="form-group mb-2 col-md-4">
          <%= form.label :latitud %>
        </div> 
        <div class="form-group mb-2 col-md-8">
          <%= form.text_field :latitud, :id => 'latitud', :readonly => "true" %>
        </div>
      </div>

      <div class="form-row">           
        <div class="form-group mb-2 col-md-4">
          <%= form.label :catalogo %>
        </div> 
        <div class="form-group mb-2 col-md-8">
          <%= form.collection_select(:catalogo_id, @valores, :id, :valor, {},{:class => "form-control chosen-select"}) %>
        </div>
      </div>

      <div class="col-lg-12">
        <div id="map" style=" height: 400px;"></div>
      </div>
      <br>
      <br>
      <div class="actions">
        <button type="submit" class="button btn btn-primary"><i class='fa fa-save'></i> Guardar</button>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){    
    $( "#inicio" ).datepicker({lenguage: 'es',format:'dd-mm-yyyy',autoclose: true});
  });
</script>

<script type="text/javascript">
  var gx_start = 14.681127723;
  var gy_start = -90.48370420;
  var map_opt = {
    zoom: 15, 
    center: new google.maps.LatLng(gx_start,gy_start), 
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    zoomControl: false,
        mapTypeControl: false,
        scaleControl: false,
        panControl: false,
        navigationControl: false,
        streetViewControl: false,
        gestureHandling: 'cooperative'
  };

  var this_map = new google.maps.Map(document.getElementById('map'),map_opt);

      //INICIAR CARGA DE DATOS
  $(document).ready(function(){
    google.maps.event.addDomListener(window, 'load', placeMarkerAndPanTo());
  });

  function placeMarkerAndPanTo() {
    google.maps.event.addListener(this_map, 'click', function(e){ 
      init_marker = new google.maps.Marker({
        position: {lat: e.latLng.lat(), lng: e.latLng.lng() },
        map: this_map,
        title: "Denuncia",
        icon: new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_bubble_icon_text_small&chld=caution|bbbr|Incidente|000066|FFFFFF")
        });
      $('#longitud').val(e.latLng.lng());
      $('#latitud').val(e.latLng.lat());
    });
  }
</script>

app/views/denuncia/edit.html.erb
<!-- Titlebar
================================================== -->
<div id="titlebar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('titulos.denuncium') %></h2>
        <!-- Breadcrumbs -->
        <nav id="breadcrumbs">
          <ul>
            <li><%= inicio %></li>
            <li><%= link_to t('titulos.denuncium'), denuncia_path %></li>
            <li><%= t('titulos.editar') %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- Content
    ================================================== -->
<section class="container">  
	<%= render 'form', denuncium: @denuncium %>
</section>

app/views/denuncia/index.html.erb
<!-- Titlebar
================================================== -->
<div id="titlebar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('titulos.denuncium') %></h2>
        <!-- Breadcrumbs -->
        <nav id="breadcrumbs">
          <ul>
            <li><%= inicio %></li>
            <li>Denuncias</li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- Content
    ================================================== -->
<section class="container">
  <p id="notice"><%= notice %></p>
  
  <div class="row">    
    <div class="col-lg-12">
      <table class="basic-table" style='<%= if usuario_signed_in? then "visibility: visible;" else "visibility: hidden;" end %>'>
        <thead class="thead-dark">
          <tr>
            <th scope="col"><%= t('activerecord.attributes.denuncium.fecha') %></th>
            <th scope="col"><%= t('activerecord.attributes.denuncium.catalogo_id') %></th>
            <th scope="col"><%= t('activerecord.attributes.denuncium.longitud') %></th>
            <th scope="col"><%= t('activerecord.attributes.denuncium.latitud') %></th>
            <th scope="col"><%= t('activerecord.attributes.denuncium.descripcion') %></th>
          </tr>
        </thead>
        <tbody>
          <% @denuncia.each do |denuncium| %>
            <tr>
              <td><%= denuncium.fecha %></td>
              <td><%= denuncium.catalogo.valor %></td>
              <td><%= denuncium.longitud %></td>
              <td><%= denuncium.latitud %></td>
              <td><%= denuncium.descripcion %></td>
              <!--td>
                <div class="btn-group" role="group">
                  <%#= link_to t('botones.editar'), edit_denuncium_path(denuncium), :class => 'button btn btn-info boton-xs' %>
                  <%#= link_to t('botones.eliminar'), denuncium, method: :delete, data: { confirm: 'Seguro que desea eliminar este denuncium?' }, :class => 'button btn btn-danger boton-xs' %>
                </div>
              </td-->
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to t('botones.nuevo'), new_denuncium_path, :class => 'button btn btn-primary' %>
      <%= link_to "EXPORTAR EXCEL", new_denuncium_path, :class => 'button btn btn-primary', :style => (if usuario_signed_in? then "visibility: visible;" else "visibility: hidden;" end) %>
    </div>
  </div>
</section>

app/views/denuncia/new.html.erb
<!-- Titlebar
================================================== -->
<div id="titlebar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('titulos.denuncium') %></h2>
        <!-- Breadcrumbs -->
        <nav id="breadcrumbs">
          <ul>
            <li><%= inicio %></li>
            <li><%= link_to t('titulos.denuncium'), denuncia_path %></li>
            <li><%= t('titulos.nuevo') %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- Content
    ================================================== -->
<section class="container">  
	<%= render 'form', denuncium: @denuncium %>
</section>

app/views/denuncia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @denuncium.fecha %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @denuncium.descripcion %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @denuncium.longitud %>
</p>

<p>
  <strong>Latitud:</strong>
  <%= @denuncium.latitud %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @denuncium.estado %>
</p>

<p>
  <strong>Catalogo:</strong>
  <%= @denuncium.catalogo %>
</p>

<%= link_to 'Edit', edit_denuncium_path(@denuncium) %> |
<%= link_to 'Back', denuncia_path %>