config/routes.rb
Rails.application.routes.draw do 
  resources :denuncia
  resources :institucioncatalogos
  resources :catalogos
  resources :institucions
  
  root :to => "institucions#index"

  resources :institucions do
    resources :institucioncatalogos
  end

  devise_for :usuarios, 
  	path: 'auth', 
  	path_names: { 
  		sign_in: 'login', 
  		sign_out: 'logout', 
  		password: 'secret', 
  		confirmation: 'verification', 
  		unlock: 'unblock', 
  		registration: 'register', 
  		sign_up: 'let_me_in' }
end

app/models/institucion.rb
class Institucion < ApplicationRecord
	before_save :to_upper

	has_many :usuarios
	has_many :institucioncatalogos

	validates :nombre, :abreviatura, :direccion, presence: true
	validates :nombre, uniqueness: true 
	validates :nombre, length: { maximum: 350 }
end

app/controllers/institucions_controller.rb
class InstitucionsController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_institucion, only: [:show, :edit, :update, :destroy]

  # GET /institucions
  # GET /institucions.json
  def index
    @institucions = Institucion.all
  end

  # GET /institucions/1
  # GET /institucions/1.json
  def show
  end

  # GET /institucions/new
  def new
    @institucion = Institucion.new
  end

  # GET /institucions/1/edit
  def edit
  end

  # POST /institucions
  # POST /institucions.json
  def create
    @institucion = Institucion.new(institucion_params)

    respond_to do |format|
      if @institucion.save
        format.html { redirect_to @institucion, notice: 'Institución se ha creado exitosamente.' }
        format.json { render :show, status: :created, location: @institucion }
      else
        format.html { render :new }
        format.json { render json: @institucion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institucions/1
  # PATCH/PUT /institucions/1.json
  def update
    respond_to do |format|
      if @institucion.update(institucion_params)
        format.html { redirect_to @institucion, notice: 'Institución se ha actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @institucion }
      else
        format.html { render :edit }
        format.json { render json: @institucion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institucions/1
  # DELETE /institucions/1.json
  def destroy
    @institucion.destroy
    respond_to do |format|
      format.html { redirect_to institucions_url, notice: 'Institución se ha eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institucion
      @institucion = Institucion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institucion_params
      params.require(:institucion).permit(:nombre, :direccion, :abreviatura)
    end
end

app/helpers/institucions_helper.rb
module InstitucionsHelper
end

app/views/institucions/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_with(model: institucion, local: true) do |form| %>
      <% if institucion.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(institucion.errors.count, "error") %> prohibited this institucion from being saved:</h2>

          <ul>
          <% institucion.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-row">           
        <div class="form-group mb-2 col-md-4"> 
          <%= form.label :nombre %>
        </div> 
        <div class="form-group mb-2 col-md-8">
          <%= form.text_field :nombre, id: :institucion_nombre %>
        </div>
      </div>

      <div class="form-row">           
        <div class="form-group mb-2 col-md-4"> 
          <%= form.label :abreviatura %>
        </div> 
        <div class="form-group mb-2 col-md-8">
          <%= form.text_field :abreviatura, id: :institucion_abreviatura %>
        </div>
      </div>

      <div class="form-row">           
        <div class="form-group mb-2 col-md-4"> 
          <%= form.label :direccion %>
        </div> 
        <div class="form-group mb-2 col-md-8">
          <%= form.text_field :direccion, id: :institucion_direccion %>
        </div>
      </div>
      <br>
      <div class="actions">
        <button type="submit" class="button btn btn-primary"><i class='fa fa-save'></i> Guardar</button>
      </div>
    <% end %>
  </div>
</div>

app/views/institucions/edit.html.erb
<!-- Titlebar
================================================== -->
<div id="titlebar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('titulos.catalogo') %></h2>
        <!-- Breadcrumbs -->
        <nav id="breadcrumbs">
          <ul>
            <li><%= inicio %></li>
            <li><%= link_to t('titulos.institucion'), institucions_path %></li>
            <li><%= t('titulos.editar') %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- Content
    ================================================== -->
<section class="container">  
	<%= render 'form', institucion: @institucion %>
</section>

app/views/institucions/index.html.erb
<!-- Titlebar
================================================== -->
<div id="titlebar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('titulos.institucion') %></h2>
        <!-- Breadcrumbs -->
        <nav id="breadcrumbs">
          <ul>
            <li><%= inicio %></li>
            <li>Instituciónes</li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- Content
    ================================================== -->

<section class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">    
    <div class="col-lg-12">
      <table class="basic-table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Código</th>
            <th scope="col"><%= t('activerecord.attributes.institucion.nombre') %></th><!--style="width: 60%"-->
            <th scope="col"><%= t('activerecord.attributes.institucion.abreviatura') %></th>
            <th scope="col"><%= t('activerecord.attributes.institucion.direccion') %></th>
            <th scope="col" colspan="2"><%= t('titulos.acciones') %></th>
          </tr>
        </thead>
        <tbody>
          <% @institucions.each do |institucion| %>
          <tr>
              <td><%= institucion.id %></td>
              <td><%= institucion.nombre %></td>
              <td><%= institucion.abreviatura %></td>
              <td><%= institucion.direccion %></td>
              <td>
                <%= link_to t('botones.tipos'), institucion_institucioncatalogos_path(institucion), :class => 'button btn btn-secondary boton-xs' %>
              </td>
              <td>
                <div class="btn-group" role="group">
                  <%= link_to t('botones.show'), institucion, :class => 'button btn btn-secondary boton-xs' %>
                  <%= link_to t('botones.editar'), edit_institucion_path(institucion), :class => 'button btn btn-info boton-xs' %>
                  <%= link_to t('botones.eliminar'), institucion, method: :delete, data: { confirm: 'Seguro que desea eliminar este institución?' }, :class => 'button btn btn-danger boton-xs' %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to t('botones.nuevo'), new_institucion_path, :class => 'button btn btn-primary' %>
    </div>
  </div>
</section>

app/views/institucions/new.html.erb
<!-- Titlebar
================================================== -->
<div id="titlebar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('titulos.catalogo') %></h2>
        <!-- Breadcrumbs -->
        <nav id="breadcrumbs">
          <ul>
            <li><%= inicio %></li>
            <li><%= link_to t('titulos.institucion'), institucions_path %></li>
            <li><%= t('titulos.nuevo') %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- Content
    ================================================== -->
<section class="container">  
	<%= render 'form', institucion: @institucion %>
</section>

app/views/institucions/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
	<div class="centrado">
		<form style="width: 350px;">  
			<div class="form-row">			     
        		<div class="form-group mb-2 col-md-4">            
		         	<p class="form-control text-primary"><%= t('activerecord.attributes.institucion.nombre') %>: </p>
		        </div> 
		        <div class="form-group mb-2 col-md-8">                       
		          	<p class="form-control"><%= @institucion.nombre %></p>	            	
		        </div>  
		    </div>
		    <div class="form-row">			     
        		<div class="form-group mb-2 col-md-4">            
		         	<p class="form-control text-primary"><%= t('activerecord.attributes.institucion.abreviatura') %>: </p>
		        </div> 
		        <div class="form-group mb-2 col-md-8">                       
		          	<p class="form-control"><%= @institucion.abreviatura %></p>	            	
		        </div>  
		    </div>
		    <div class="form-row">			     
        		<div class="form-group mb-2 col-md-4">            
		         	<p class="form-control text-primary"><%= t('activerecord.attributes.institucion.direccion') %>: </p>
		        </div> 
		        <div class="form-group mb-2 col-md-8">                       
		          	<p class="form-control"><%= @institucion.direccion %></p>	            	
		        </div>  
		    </div>		    	    	    	      	
	    </form>
  	</div>
</div>

<%= link_to t('titulos.editar'), edit_institucion_path(@institucion) %> |
<%= link_to t('titulos.regresar'), institucions_path %>