config/routes.rb
Rails.application.routes.draw do 
  resources :denuncia
  resources :institucioncatalogos
  resources :catalogos
  resources :institucions
  
  root :to => "institucions#index"

  resources :institucions do
    resources :institucioncatalogos
  end

  devise_for :usuarios, 
  	path: 'auth', 
  	path_names: { 
  		sign_in: 'login', 
  		sign_out: 'logout', 
  		password: 'secret', 
  		confirmation: 'verification', 
  		unlock: 'unblock', 
  		registration: 'register', 
  		sign_up: 'let_me_in' }
end

app/models/institucioncatalogo.rb
class Institucioncatalogo < ApplicationRecord
	belongs_to :catalogo
	belongs_to :institucion

	validates_uniqueness_of :catalogo_id, scope: :institucion_id
end

app/controllers/institucioncatalogos_controller.rb
class InstitucioncatalogosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_institucioncatalogo, only: [:show, :edit, :update, :destroy]

  # GET /institucioncatalogos
  # GET /institucioncatalogos.json
  def index
    @institucion = Institucion.where(:id => params[:institucion_id]).first
    @institucioncatalogos = Institucioncatalogo.where(:institucion_id => params[:institucion_id])
  end

  # GET /institucioncatalogos/1
  # GET /institucioncatalogos/1.json
  def show
  end

  # GET /institucioncatalogos/new
  def new
    #raise params[:institucion_id].to_json
    @institucion = Institucion.where(:id => params[:institucion_id]).first
    #raise @institucion.to_json
    @valores = Catalogo.all
    @institucioncatalogo = Institucioncatalogo.new
    @institucioncatalogo.institucion_id = params[:institucion_id]
  end

  # GET /institucioncatalogos/1/edit
  def edit
    @valores = Catalogo.all
    @institucion = Institucion.where(:id => params[:institucion_id]).first
  end

  # POST /institucioncatalogos
  # POST /institucioncatalogos.json
  def create
    @valores = Catalogo.all
    @institucion = Institucion.where(:id => institucioncatalogo_params['institucion_id']).first
    @institucioncatalogo = Institucioncatalogo.new(institucioncatalogo_params)

    respond_to do |format|
      if @institucioncatalogo.save
        format.html { redirect_to institucion_institucioncatalogos_url(@institucion), notice: 'El registro se ha creado exitosamente.' }
        format.json { render :show, status: :created, location: @institucioncatalogo }
      else
        format.html { render :new }
        format.json { render json: @institucioncatalogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institucioncatalogos/1
  # PATCH/PUT /institucioncatalogos/1.json
  def update
    @valores = Catalogo.all
    @institucion = Institucion.where(:id => institucioncatalogo_params['institucion_id']).first
    respond_to do |format|
      if @institucioncatalogo.update(institucioncatalogo_params)
        format.html { redirect_to institucion_institucioncatalogos_url(@institucion), notice: 'El registro se ha actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @institucioncatalogo }
      else
        format.html { render :edit }
        format.json { render json: @institucioncatalogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institucioncatalogos/1
  # DELETE /institucioncatalogos/1.json
  def destroy
    @institucion = Institucion.find(params[:institucion_id])
    @institucioncatalogo.destroy
    respond_to do |format|
      format.html { redirect_to institucion_institucioncatalogos_url(@institucion), notice: 'El registro se ha eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institucioncatalogo
      @institucioncatalogo = Institucioncatalogo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institucioncatalogo_params
      params.require(:institucioncatalogo).permit(:catalogo_id, :institucion_id)
    end
end

app/helpers/institucioncatalogos_helper.rb
module InstitucioncatalogosHelper
end

app/views/institucioncatalogos/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_with(model: institucioncatalogo, local: true) do |form| %>
      <% if institucioncatalogo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(institucioncatalogo.errors.count, "error") %> prohibited this institucioncatalogo from being saved:</h2>

          <ul>
          <% institucioncatalogo.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-row">           
        <div class="form-group mb-2 col-md-3">            
          <%= form.label :institucion_id, :class => 'form-control-plaintext'%>                   
        </div> 
        <div class="form-group mb-2 col-md-1" style="visibility: hidden;">                       
          <%= form.text_field :institucion_id, :class => 'form-control'%>
        </div>    
        <div class="form-group mb-2 col-md-8">
          <input type="text" class="form-control" disabled="true" value='<%= @institucion.nombre %>'></input>
        </div>             
      </div>

      <div class="form-row">           
        <div class="form-group mb-2 col-md-4"> 
          <%= form.label :catalogo %>
        </div> 
        <div class="form-group mb-2 col-md-8">
          <%= form.collection_select(:catalogo_id, @valores, :id, :valor, {},{:class => "form-control chosen-select"}) %>
        </div>
      </div>

      <br>
      <div class="actions">
        <button type="submit" class="button btn btn-primary"><i class='fa fa-save'></i> Guardar</button>
      </div>
    <% end %>
  </div>
</div>

app/views/institucioncatalogos/edit.html.erb
<!-- Titlebar
================================================== -->
<div id="titlebar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('titulos.catalogo') %></h2>
        <!-- Breadcrumbs -->
        <nav id="breadcrumbs">
          <ul>
            <li><%= inicio %></li>
            <li><%= link_to t('titulos.institucion'), institucions_path %></li>
            <li><%= link_to t('titulos.catalogo'), institucion_institucioncatalogos_path(@institucion) %></li>
            <li><%= t('titulos.editar') %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- Content
    ================================================== -->
<section class="container">  
	<%= render 'form', institucioncatalogo: @institucioncatalogo %>
</section>

app/views/institucioncatalogos/index.html.erb
<!-- Titlebar
================================================== -->
<div id="titlebar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('titulos.insticata') %></h2>
        <!-- Breadcrumbs -->
        <nav id="breadcrumbs">
          <ul>
            <li><%= inicio %></li>
            <li><%= link_to t('titulos.institucion'), institucions_path %></li>
            <li>Catálogos</li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- Content
    ================================================== -->
<section class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">    
    <div class="col-lg-12">
      <table class="basic-table">
        <thead class="thead-dark">
          <tr>
            <th scope="col"><%= t('activerecord.attributes.institucioncatalogo.catalogo_id') %></th>
            <th scope="col"><%= t('activerecord.attributes.institucioncatalogo.institucion_id') %></th>
            <th scope="col"><%= t('titulos.acciones') %></th>
          </tr>
        </thead>
        <tbody>
          <% @institucioncatalogos.each do |institucioncatalogo| %>
            <tr>
              <td><%= institucioncatalogo.catalogo.valor %></td>
              <td><%= institucioncatalogo.institucion.abreviatura %></td>
              <td>
                <div class="btn-group" role="group">                 
                  <%= link_to t('botones.editar'), edit_institucion_institucioncatalogo_path(@institucion,institucioncatalogo), :class => 'button btn btn-info boton-xs' %>
                  <%= link_to t('botones.eliminar'), institucion_institucioncatalogo_path(@institucion, institucioncatalogo), method: :delete, data: { confirm: 'Seguro que desea eliminar este catálogo?' }, :class => 'button btn btn-danger boton-xs' %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to t('botones.nuevo'), new_institucion_institucioncatalogo_path(@institucion), :class => 'button btn btn-primary' %>
    </div>
  </div>
</section>

app/views/institucioncatalogos/new.html.erb
<!-- Titlebar
================================================== -->
<div id="titlebar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('titulos.catalogo') %></h2>
        <!-- Breadcrumbs -->
        <nav id="breadcrumbs">
          <ul>
            <li><%= inicio %></li>
            <li><%= link_to t('titulos.institucion'), institucions_path %></li>
            <li><%= link_to t('titulos.catalogo'), institucion_institucioncatalogos_path(@institucion) %></li>
            <li><%= t('titulos.nuevo') %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- Content
    ================================================== -->
<section class="container">  
	<%= render 'form', institucioncatalogo: @institucioncatalogo %>
</section>

app/views/institucioncatalogos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Catalogo:</strong>
  <%= @institucioncatalogo.catalogo %>
</p>

<p>
  <strong>Institucion:</strong>
  <%= @institucioncatalogo.institucion %>
</p>

<%= link_to 'Edit', edit_institucioncatalogo_path(@institucioncatalogo) %> |
<%= link_to 'Back', institucioncatalogos_path %>